package org.jboss.qa.perfrepo.web.util;

import org.jboss.qa.perfrepo.model.report.Report;
import org.jboss.qa.perfrepo.model.report.ReportProperty;

import java.util.Map;

public class ReportUtils {

	/**
	 * Creates new ReportProperty object with given attributes. It's a helper method for creating
	 * these objects.
	 *
	 * @param name
	 * @param value
	 * @param report
	 * @return newly created {@link ReportProperty} object
	 */
	public static ReportProperty createReportProperty(String name, String value, Report report) {
		ReportProperty reportProperty = new ReportProperty();
		reportProperty.setName(name);
		reportProperty.setValue(value);
		reportProperty.setReport(report);

		return reportProperty;
	}

	/**
	 * Helper method. It performs an update in map of report properties, if the property already exists. If not,
	 * it creates new one. This method exists because if the ReportProperty already exists, we must not
	 * create a new object, because it would have new autogenerated ID. Instead, we modify the existing one.
	 *
	 * @param reportProperties
	 * @param name
	 * @param value
	 * @param report
	 */
	public static void createOrUpdateReportPropertyInMap(Map<String, ReportProperty> reportProperties, String name, String value, Report report) {
		if (reportProperties.containsKey(name)) {
			reportProperties.get(name).setValue(value);
		} else {
			reportProperties.put(name, ReportUtils.createReportProperty(name, value, report));
		}
	}
}
