package org.jboss.qa.perfrepo.util;

import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang.StringEscapeUtils;
import org.jboss.qa.perfrepo.model.TestExecutionParameter;
import org.jboss.qa.perfrepo.model.report.Report;
import org.jboss.qa.perfrepo.model.report.ReportProperty;

/**
 * 
 * Various utility methods.
 * 
 * @author Michal Linhard (mlinhard@redhat.com)
 * 
 */
public class Util {

   /**
    * Parses space separated tags into a list.
    * 
    * @param tags
    * @return List of tags
    */
   public static List<String> parseTags(String tags) {
      if (tags == null) {
         return Collections.emptyList();
      } else {
         String trimmed = tags.trim();
         if ("".equals(trimmed)) {
            return Collections.emptyList();
         } else {
            return Arrays.asList(trimmed.split(" "));
         }
      }
   }

   public static String rawTags(List<String> tags) {
      if (tags == null || tags.isEmpty()) {
         return "";
      }
      StringBuffer s = new StringBuffer(tags.get(0));
      for (int i = 1; i < tags.size(); i++) {
         s.append(" ");
         s.append(tags.get(i));
      }
      return s.toString();
   }

   public static String displayValue(TestExecutionParameter param) {
      if (param == null) {
         return "&nbsp;";
      }
      String value = param.getValue();
      if (value == null) {
         return "&nbsp;";
      }
      if (value.startsWith("http://") || value.startsWith("https://")) {
         if (value.length() > 100) {
            return "<a href=\"" + value + "\">" + value.substring(0, 96) + " ...</a>";
         } else {
            return "<a href=\"" + value + "\">" + value + "</a>";
         }
      } else if (value.length() > 100) {
         return "<a href=\"/repo/param/" + param.getId() + "\">" + StringEscapeUtils.escapeHtml(value.substring(0, 96)) + " ...</a>";
      } else {
         return StringEscapeUtils.escapeHtml(value);
      }
   }

   public static String format4(double val) {
      return new DecimalFormat("0.0000").format(val);
   }

   /**
    * @param a
    * @param s
    * @return True iff array a contains string s
    */
   public static boolean contains(String[] a, String s) {
      if (a == null) {
         return false;
      }
      for (String e : a) {
         if (e.equals(s)) {
            return true;
         }
      }
      return false;
   }

   /**
    * 
    * @param s1
    * @param s2
    * @return True iff all strings from s1 are contained in s2
    */
   public static boolean isSubset(String[] s1, String[] s2) {
      for (String s : s1) {
         if (!contains(s2, s)) {
            return false;
         }
      }
      return true;
   }

   /**
    * Creates new ReportProperty object with given attributes. It's a helper method for creating
    * these objects.
    *
    * @param name
    * @param value
    * @param report
    * @return newly created {@link ReportProperty} object
    */
   public static ReportProperty createReportProperty(String name, String value, Report report) {
      ReportProperty reportProperty = new ReportProperty();
      reportProperty.setName(name);
      reportProperty.setValue(value);
      reportProperty.setReport(report);

      return reportProperty;
   }

   /**
    * Helper method. It performs an update in map of report properties, if the property already exists. If not,
    * it creates new one. This method exists because if the ReportProperty already exists, we must not
    * create a new object, because it would have new autogenerated ID. Instead, we modify the existing one.
    *
    * @param reportProperties
    * @param name
    * @param value
    * @param report
    */
   public static void createOrUpdateReportPropertyInMap(Map<String, ReportProperty> reportProperties, String name, String value, Report report) {
      if(reportProperties.containsKey(name)) {
         reportProperties.get(name).setValue(value);
      }
      else {
         reportProperties.put(name, Util.createReportProperty(name, value, report));
      }
   }
}
